server:
  port: 8010
  servlet:
    context-path: /weather-recorder

spring:
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: qwerty
    driverClassName: org.postgresql.Driver

logging:
  level:
    web: TRACE
  org:
    springframework:
      web: TRACE


#springdoc:
##  api-docs:
##    path: /api-docs # Specify the path of the OpenAPI documentation
#  swagger-ui:
#    enabled: true # Enable or disable Swagger UI
##    path: /swagger-ui.html # Specify the path of the Swagger UI